version: '3.8'
services:
  backend:
    image: 'ghcr.io/codehavenx/edifikana-backend:latest'
    restart: unless-stopped
    environment:
      - EDIFIKANA_SUPABASE_KEY=${EDIFIKANA_SUPABASE_KEY}
      - EDIFIKANA_SUPABASE_URL=${EDIFIKANA_SUPABASE_URL}
      - EDIFIKANA_ALLOWED_HOST=${EDIFIKANA_ALLOWED_HOST}
  frontend:
    image: 'ghcr.io/codehavenx/edifikana-frontend:latest'
    restart: unless-stopped
